apiVersion: v1
kind: Service
metadata:
  name: kf2-web
  namespace: killingfloor2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: kf2-server
  ports:
    - name: webadmin
      port: 8080
      targetPort: 8080
      protocol: TCP
