apiVersion: v1
kind: Service
metadata:
  name: kf2-game
  namespace: killingfloor2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: kf2-server
  ports:
    - name: game
      port: 7777
      targetPort: 7777
      protocol: UDP
    - name: query
      port: 27015
      targetPort: 27015
      protocol: UDP
    - name: steam
      port: 20560
      targetPort: 20560
      protocol: UDP
